inputs:
  tags:
    description: 'Tags to be passed to twister when running tests.'
    required: false
    default: ''
  asserts:
    description: 'asserts'
    required: false
    default: 'none'
runs:
  using: 'composite'
  steps:

    - name: Install west and dependencies
      shell: sh
      run: |
        pip3 install -U pip
        pip3 install -U setuptools
        pip3 install -U -r scripts/requirements.txt

    - name: Install zcbor package
      shell: sh
      run: |
        python3 setup.py sdist bdist_wheel
        pip3 install dist/zcbor-*.tar.gz
        pip3 uninstall -y zcbor
        pip3 install dist/zcbor-*.whl

    - name: Install packages
      shell: sh
      run: |
        sudo apt update
        sudo apt install -y gcc-multilib

    - name: Clone zephyr
      if: ${{ inputs.asserts != 'none' }}
      working-directory: tests
      shell: sh
      run: |
        git clone --depth 1 https://github.com/zephyrproject-rtos/zephyr

    - name: West init
      if: ${{ inputs.asserts != 'none' }}
      working-directory: tests
      shell: sh
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        export ZEPHYR_TOOLCHAIN_VARIANT=host
        export PATH="$HOME/.local/bin:$PATH"
        west init -l zephyr

    - name: Install twister dependencies
      if: ${{ inputs.asserts != 'none' }}
      working-directory: tests
      shell: sh
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        pip3 install -U -r $ZEPHYR_BASE/scripts/requirements-build-test.txt
        pip3 install -U -r $ZEPHYR_BASE/scripts/requirements-run-test.txt

    - name: Run tests
      if: ${{ inputs.asserts == 'without' || inputs.asserts == 'both' }}
      working-directory: tests
      shell: sh
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        export ZEPHYR_TOOLCHAIN_VARIANT=host
        $ZEPHYR_BASE/scripts/twister -i -T . -W --platform native_posix --platform native_posix_64 -t ${{ inputs.tags }}

    - name: Run tests with asserts
      if: ${{ inputs.asserts == 'with' || inputs.asserts == 'both' }}
      working-directory: tests
      shell: sh
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        export ZEPHYR_TOOLCHAIN_VARIANT=host
        $ZEPHYR_BASE/scripts/twister -i -T . -W --platform native_posix --platform native_posix_64 -t ${{ inputs.tags }} -x VERBOSE=ON -x ASSERTS=ON
