name: Run tests

on: [pull_request]

env:
  ZEPHYR_SDK_VERSION: 0.15.2

jobs:
  release-test-1:
    runs-on: ubuntu-22.04
    name: Release tests 1 (Fuzz)
    if: "startswith(github.head_ref, 'release/')"
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install zcbor
      uses: ./.github/actions/install_zcbor

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y afl++

    - name: Run pet fuzz tests
      working-directory: tests/fuzz
      run: |
        ./test-afl.sh 4 64 pet

    - name: Rename fuzz failures
      if: ${{ failure() }}
      working-directory: tests/fuzz/build-afl/output/default/crashes/
      run: |
        for i in ./* ; do mv "$i" "${i//:/_}_1"; done

    - name: Upload fuzz failures
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: fuzz-failures
        path: tests/fuzz/build-afl/output/default/crashes/

    - name: Upload release files
      uses: actions/upload-artifact@v3
      with:
        name: zcbor-release
        path: dist/*
